#include "common.h"
#include "platform.c"

// output file can look like
// // This file has been generated by meta.c
// For now, recreate it everytime you run

// todo
// clean up strings and print them
// write them to a file

#include <string.h>
b32 match_word(char* start, const char* match, u32 size)
{
    if(memcmp(start, match, size) == 0)
    {
        return true;
    }
    
    return false;
}

#define enum_gen "gen_string_from_enum"
u32 enum_gen_size = strlen(enum_gen);

b32 extract(char* start)
{
    // verify
    char* peek = start + enum_gen_size;
    ++peek;
    
    if(match_word(peek, "enum", strlen("enum")))
    {
        peek += strlen("enum");
        
        while(*(++peek) != '{')
        {
            
        }
        
        // remove {
        ++peek;
        
        i32 len = 0;
        char* beg = peek;
        
        while(*(++peek) != '}')
        {
            len++;
            if(*peek == ',')
            {
                char buffer[128] = {0};
                memcpy(buffer, beg, len);
                printf("%s\n", buffer);
                
                beg = peek;
                len = 0;
            }
        }
        return true;
    }
    
    return false;
}

int main(int argc, char* argv[])
{
    struct Arena arena;
    arena_innit(&arena, Megabytes(1), calloc(Megabytes(1),sizeof(u8)));
    char* data = yk_read_text_file("../src/assembler.c", &arena);
    
    //printf("%s",data);
    
    char* peek = data;
    
    
    while(*(++peek) != '\0')
    {
        if(*peek == 'g')
        {
            if(match_word(peek, enum_gen, enum_gen_size ))
            {
                if(extract(peek))
                {
                    break;
                }
                //printf("%s",peek);
                //break;
            }
        }
    }
    return 0;
}